### ISSUE TITLE
Trusty / Precise apt sources wrong way round on website

### ISSUE THREAD

**Issue by ali-graham** [flapjack/flapjack.io#14]
On http://flapjack.io/docs/1.0/usage/Installation/, where it describes installation on Debian, Ubuntu, the line reads:
```bash
# Ubuntu Trusty
echo 'deb http://packages.flapjack.io/deb precise main' | sudo tee  /etc/apt/sources.list.d/flapjack.list
# Ubuntu Precise
echo 'deb http://packages.flapjack.io/deb trusty main' | sudo tee  /etc/apt/sources.list.d/flapjack.list
```

This should be:
```bash
# Ubuntu Precise
echo 'deb http://packages.flapjack.io/deb precise main' | sudo tee  /etc/apt/sources.list.d/flapjack.list
# Ubuntu Trusty
echo 'deb http://packages.flapjack.io/deb trusty main' | sudo tee  /etc/apt/sources.list.d/flapjack.list
```

(Moved from https://github.com/flapjack/flapjack/issues/755.)

**Comment by Hobbsee** [comment]
> actually on further inspection there are no trusty packages on the site, and the precise package url should be:
http://packages.flapjack.io/deb/v1/

From @nielsgoossens

**Comment by Hobbsee** [comment]
Thanks - fixed up the package URL.  The trusty packages exist (and work), however, the directory indexing needs to be rebuilt.

**Comment by jessereynolds** [comment]
Directory indexes have been rebuilt now, see http://packages.flapjack.io/deb/v1/pool/main/f/flapjack/
