### ISSUE TITLE
"Gateway configuration" section report 404

### ISSUE THREAD

**Issue by pengyao** [flapjack/flapjack.io#17]
"Gateway configuration" section report 404 in http://flapjack.io/docs/1.0/

**Comment by jessereynolds** [comment]
Thanks @pengyao ! Will fix asap...

**Comment by jessereynolds** [comment]
@Hobbsee maybe moving these to their own section has broken these links? @pengyao do you know if these just broke today, or maybe a few weeks ago?

**Comment by Hobbsee** [comment]
@jessereynolds Yep, I broke it when moving to a directory with a space in it - oops.

I've now solved this properly.  Thanks for the report, @pengyao!
