### ISSUE TITLE
Document the details of notification routing

### ISSUE THREAD

**Issue by necula01** [flapjack/flapjack.io#20]
I have tried to decode the logic for processing events and generating notifications (for 1.5.0). I will post a pull request with documentation.

**Comment by necula01** [comment]
What I think would be very useful is a use-case document, where we write down several common scenarios and then we think how to achieve them with contacts/media/notification rules.

**Comment by jessereynolds** [comment]
Definitely agree with this and with the use-case / howto document to cover common scenarios.
